name: locatinsharing
description: Location Sharing System Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  contacts_service: ^0.6.3
  flutter_sms: ^2.3.3
  fast_contacts: 1.0.0

  #flutter_contacts:
  flutter:
    sdk: flutter


  custom_text_field: 0.0.3
  cupertino_icons: ^1.0.2
  #  flutter_native_splash: ^2.0.2
  #  cached_network_image: ^3.2.0
  flutter_map: ^3.1.0
  #  carousel_slider: ^4.0.0
  provider: ^6.0.5
  location: ^4.4.0
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0
  flutter_dotenv: ^5.0.2
  mapbox_gl: ^0.16.0
  google_nav_bar: 5.0.6
  google_fonts: ^4.0.3
  http: ^0.13.5
  lite_rolling_switch: ^1.0.1
  flutter_svg: ^2.0.4
  #  flutter_svg: ^0.19.0
  device_preview: ^0.1.4-beta
  fluttertoast: ^8.2.1
  mapbox_search_flutter: any
  dio: ^5.1.1
  #  geocoder: ^0.2.1
  geocoding: ^2.1.0
  flutter_mapbox_navigation: ^0.0.26
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.10
  #  firebase_auth: ^4.2.2
  #  mapbox_navigation: ^1.0.4
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_contacts: ^1.1.6
  flutter_android_volume_keydown: ^1.0.0
#  flutter_local_notifications: ^8.2.0
#  firebase_messaging: ^14.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Logo-01.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - images/
    #   - images/a_dot_ham.jpeg
    - assets/config/

